### PR TITLE
Truncate the insanely long preview lines

### LINKED ISSUE #543: Clap preview is slow if the preview line is insanely long
**Environment (please complete the following information):**
 - OS: Linux Exherbo
 - (Neo)Vim version: https://gist.github.com/hasufell/0e61d233c0ca963b26b3d54ba7442758
 - vim-clap version: 5f239116f1b428dcb7a132806d7808225aa095f5
 - Have you reproduced with a minimal vimrc: yes
 - Have you updated to the latest plugin version: yes
 - Have you upgraded to/compiled the latest Rust binary: yes

**Describe the bug**

When there's a semi-large json file in the repository with the whole payload on one line, vim-clap gets sluggish and unresponsive when walking over that file in `Clap files`. I have a suspicion that it's trying to render the entire line, no matter how long it is.

**Clap debug**

```

            has cargo: 1
            has maple: /home/jule/.cache/dein/repos/github.com/liuchengxu/vim-clap/target/release/maple
           maple info: version 0.1.21 (git v0.21-2-g5f23911), built for x86_64-unknown-linux-gnu by rustc 1.42.0-nightly (3bf71b3d5 2020-01-25).

         has +python3: 1
has py dynamic module: 1
            has ctags: ctags with JSON output support
     Current FileType: 
Third Party Providers: []
       Global Options:
    let g:clap#autoload_dir = '/home/jule/.cache/dein/repos/github.com/liuchengxu/vim-clap/autoload'
    let g:clap#popup#display = {'shrink': function('71'), 'open': function('<SNR>103_create_display'), 'shrink_if_undersize': function('70')}
    let g:clap#popup#preview = {'line_count': function('<SNR>102__line_count'), 'show': function('72'), 'hide': function('73'), 'add_highlight': function('74'), 'get_lines': function('<SNR>102__get_lines'), 'getbufvar': function('<SNR>102__getbufvar'), 'setbufvar_batch': function('<SNR>102__setbufvar_batch'), 'setbufvar': function('<SNR>102__setbufvar'), 'win_is_valid': function('<SNR>102__win_is_valid'), 'goto_win': function('<SNR>102__goto_win'), 'set_syntax': function('75')}
    let g:clap#provider_alias = {'gfiles': 'git_files', 'hist:': 'command_history', 'hist/': 'search_history'}
    let g:clap_disable_bottom_top = 0
    let g:clap_disable_matches_indicator = v:false
    let g:clap_disable_optional_async = v:false
    let g:clap_disable_run_rooter = v:false
    let g:clap_enable_debug = v:false
    let g:clap_enable_icon = 0
    let g:clap_forerunner_status_sign = {'done': '•', 'running': '!', 'using_cache': '*'}
    let g:clap_insert_mode_only = v:false
    let g:clap_layout = {'col': '5%', 'row': '33%', 'width': '95%', 'relative': 'editor', 'height': '33%'}
    let g:clap_multi_selection_warning_silent = 0
    let g:clap_no_matches_msg = 'NO MATCHES FOUND'
    let g:clap_open_action = {'ctrl-v': 'vsplit', 'ctrl-x': 'split', 'ctrl-t': 'tab split'}
    let g:clap_popup_border = 'rounded'
    let g:clap_preview_size = 5
    let g:clap_providers_relaunch_code = '@@'
    let g:clap_search_box_border_style = 'nil'
    let g:clap_search_box_border_symbols = {'nil': ['', ''], 'curve': ['', ''], 'arrow': ['', '']}
    let g:clap_use_pure_python = 1
  Provider Variables:
                     []
```

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-clap
syntax on
filetype plugin indent on
```
2. Put this file into a repo: https://gist.github.com/hasufell/e7507d33552d3acf692700dfffa8a914

3. Start (neo)vim with command: `vim -u min.vim` from inside that repo

4. See slow behavior

**Expected behavior**

Clap is reponsive.

### PR DESCRIPTION
**Pull request by liuchengxu**
Close #543

### CODE REVIEW

File: crates/stdio_server/src/session/handler/on_move.rs [hunk 1]
```diff
@@ -178,6 +178,14 @@ impl<'a> OnMoveHandler<'a> {
...
             Ok((lines_iter, hi_lnum)) => {
                 let fname = format!("{}", path.as_ref().display());
+                let max_width = 2 * self.context.winwidth.unwrap_or(100) as usize;
+                let lines_iter = lines_iter.map(|line| {
+                    if line.len() > max_width {
+                        format!("{}......", &line[..max_width])
+                    } else {
+                        line
+                    }
+                });
```
Comment (liuchengxu) [inline crates/stdio_server/src/session/handler/on_move.rs:188]: @ImmemorConsultrixContrarie Any insight to fix the code repeatation here?

Comment (ImmemorConsultrixContrarie) [reply crates/stdio_server/src/session/handler/on_move.rs:188]:
```rust
impl Whatever {
    fn preview_truncation<S: Borrow<str>>(&self, lines: impl Iterator<Item=S>) -> impl Iterator<Item=String> {
        let max_width = 2 * self.context.winwidth.unwrap_or(100) as usize;
        let lines_iter = lines_iter.map(move |line| {
            let line = line.borrow();
            if line.len() > max_width {
                format!("{}......", &line[..max_width])
            } else {
                line
            }
        });
    }
}
```

Comment (liuchengxu) [reply crates/stdio_server/src/session/handler/on_move.rs:188]: `move` does the trick. 🎉

Comment (ImmemorConsultrixContrarie) [reply crates/stdio_server/src/session/handler/on_move.rs:188]: Btw, It's better to change
`format!("{}......", &line[..max_width])`
into
```rust
line.truncate(max_width);
line.push_str("……");
line
```

to avoid unnecessary allocation here.

Comment (ImmemorConsultrixContrarie) [reply crates/stdio_server/src/session/handler/on_move.rs]: Also, string index could panic if you would accidentally point into the middly of multibyte char. Probably one of `str` methods could help with this.

Comment (ImmemorConsultrixContrarie) [reply crates/stdio_server/src/session/handler/on_move.rs]: Okay, it probably should be written as

```rust
line.truncate((0..max_width).find(|idx| line.is_char_boundary(idx)).unwrap());
line.push_str("……");
line
```

@liuchengxu

Comment (ImmemorConsultrixContrarie) [reply crates/stdio_server/src/session/handler/on_move.rs]: This thing won't panic. However, for *multichar* sequences this could show a wrong thing, like showing 👩 or 🔬 emoji instead of 👩‍🔬 .

Comment (ImmemorConsultrixContrarie) [reply crates/stdio_server/src/session/handler/on_move.rs]: Unicode strings are hard, yes.

**Comment by hasufell** [comment]
Does this truncate after it read the entire line? It should only read the line up to X bytes in the first place.

**Comment by liuchengxu** [comment]
>Does this truncate after it read the entire line? It should only read the line up to X bytes in the first place.

Yeah, that's even better, but the current approach already wont slow down vim as it's async.

**Comment by ImmemorConsultrixContrarie** [comment]
> Does this truncate after it read the entire line? It should only read the line up to X bytes in the first place.

Nope, to do so you need to customize the reader, by default it reads until meats newline. Not too hard to do, yet a little tricky.

File: crates/stdio_server/src/session/handler/on_move.rs (hunk 1 above)
Comment (liuchengxu) [reply crates/stdio_server/src/session/handler/on_move.rs]: Yes, master, I'm on it...

**Comment by hasufell** [comment]
I tried this branch and I believe it still reads the entire file. It's not as bad as before, but when I go over the offending file, memory consumption of vim goes up from 14mb to ~100mb.

**Comment by liuchengxu** [comment]
Merged. @hasufell Thanks for confirming! And thanks for the Rust expert! @ImmemorConsultrixContrarie
